/* auto-generated by makeNewFile */
/* compiled at 2021-02-04 12:29:03.845629 */
/* created by llamaking136 */
/*
Copyright 2021 llamaking136

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

#if !defined(LIB_HPP)
#define LIB_HPP

#include <ctime>
#include <iostream>
#include <string>
#include <cstring>
#include <sstream>
#include <fstream>
#include <sys/stat.h>
#include "../source/error.hpp"

namespace lib {
    int strlen(const char* text);

    std::string chartostr(const char* text);

    char* gettime();

    void log(std::string text, bool regout);

    void logError(std::string text, bool isError);

    template <typename T>
    void print_vector(T data);

    char inttochar(int val);

    std::string fileread(std::string filename);

	std::vector<std::string> stringtok(std::string, char);

	bool is_dir(const char*);
}

#endif /* LIB_HPP */
